/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c5474ce7-6b31-4b4d-be01-173886c8c134",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8SVQe8Kv5",
    "aws_user_pools_web_client_id": "43mtm37q0mpvnkeq1pia7a4f8n",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://z3qoiavykzcjbmnaid3whgzhxi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "seekseniorprojectd73987c00ca7454dade2e648928581152527-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
